conf.php
Implemented these base vars:
- `dataFileName`
- `allowOneTimeImport`
- `allowConstantRefresh`
- `maxRefreshTime`
=> Implemented base vars

functions.php, index.php, job.json
Created `index.php` and `functions.php`
In `index.php` added a simple html layout of all the data that will be presented. The information is generated by calling `displayJSONDataToTable()` function inside `functions.php`. In addition, the formatting of the frequency int to string is handled in the function `frequencyToText()`
=> Created a table with info about links in JSON file

add.php, functions.php, index.php, job.json, validate.php
- Created `add.php` page which shows and handles new playlist submission.
- Added a new function in `functions.php` which helps with validation.
- Added a button for adding playlists in `index.php`.
- Added validation rules in `validate.php`.
=> Added function for playlist addition

index.php
in the `index.php` file I added a javascript code which would count down till the next hour.
=> Added a countdown timer till the beginning of next hour

add.php, conf.php, validate.php
Reverts archlich03/spotify-link-to-json#12
=> Revert "Simplified the validation code in add.php"

add.php, edit.php, functions.php, validate.php
- New page called `edit.php` meant for... editing. Found data (by ID) is shown in the input fields, where it can be changed. 
- Added two functions to `functions.php` which cut down code reuse.
=> Added page and functions for editing

add.php, edit.php, job.json, validate.php
- created a value `frequencyMinValue` to specify what the min value should be in forms
- added more in-depth error handling and added error messages for the `allowOneTimeImport`, `allowConstantRefresh`, `maxRefreshTime`
- improved outputting syntax
=> Implemented conf variable error handling

functions.php
- Modified the `readJSON` function to check if the file exists before performing operations.
- changed the `displayJSONDataToTable` function to work with readJSON. (Since readJSON returns an associative array instead of object, the logic needed to be altered)
=> Added checks for JSON existance

add.php, delete.php, edit.php, functions.php, index.php, validate.php
- A page for deletion titled `delete.php`. It splices the entry from the loaded JSON file and then re-encodes it.
- Functions which lessen code reuse. (Same ones from [Edit PR](https://github.com/archlich03/spotify-link-to-json/pull/8))
=> Added functions and page for deletion

download.php, functions.php, index.php
Things added:
- Added a `download.php` page which allows to select file format and download the file.
- Additional functions in `functions.php` which handle JSON conversion to CSV and TXT
- Added href for page access in `index.php`.
=> Added a download function

functions.php
- Readded a ternary if statement that was lost during merge in `functions.php`
- Changed the readJSON function to create an empty JSON file if one doesn't exist already.
=> Changed function to create empty JSON

index.php, sitemap.html
=> Created a simple sitemap

add.php, delete.php, download.php, edit.php, index.php, sitemap.html
Self-explanatory. Added metadata in all visible pages.
=> Added basic metadata

index.php
Added an even listener which allows to manually inititate check script. MERGE AFTER [TIMER PR](https://github.com/archlich03/spotify-link-to-json/pull/38)
=> Added an event listener to manually check

add.php, download.php, index.php, sitemap.php, style.css
Added styling using CSS. Initial version, mention anything that should look different.
=> Added first version of styling.

index.php, template/footer.php
Added a message for better responsiveness and clarity when refresh is initiated.
=> Added a message to show that refresh starts.

scripts/readjson.py
code is self explanitory.
Could you please test it on your end? You have a better version set up locally
=> Added to the verbosity of `readjson.py`

template/footer.php
Changed authors list. Very complex.
=> Changed authors

register.php, sqlsetup.php
Added uniqueness checks in registration page and a `UNIQUE` rule in DB creation.
=> 66 make usernames unique

login.php
Changed login form submission logic from GET to POST so the information doesn't get show in the URL.
=> Changed login from GET to POST for security

functions.php, register.php
Fixed security oversight which allowed a user to download all entries.
=> Fixed security flaw

functions.php, profile.php, template/header.php
Added ability to change a user's password. Hashes input, then compares with hashed password in DB. If true, allows to be changed. Also checks if new password isn't weak.
=> Allow password changing

functions.php, register.php
Added server-side and client-side checks for password/username length to avoid flooding DB.
=> Added character limits to password and username.

README.md
Updated parts regarding PHP installation in the setup guide.
=> Updated PHP instalation section

bodies/index.php
Added a current total disk usage monitoring progress bar. When a user is an admin, in the overview window, they will see an additional container, which shows the current total disk usage of the system. Used color schema for the progress bar in relation to the used disk space:
- `<75%`: green
- `75% - 90%`: orange
- `>90%`: red
=> Added disk usage statistics

README.md, scripts/readDB.py
Self explanitory. Really difficult PR
=> Edited old DB connection sample values

edit.php
Fixed typo, which prevented the old values, that are being edited, from appearing
=> Fixed playlist values not appearing when editing

bodies/profile.php, profile.php, register.php
Added pasword confirmation to:
- registration form (`register.php`)
- user's self password change (`profile.php`)
=> Added confirmation to registration, profile pages

README.md, scripts/readDB.py
Added SpotDL version auto-detection using `glob`. Changed setup instructions accordingly.
=> Add version auto-detect

login.php, register.php
=> Changed font to Sans-serif

README.md
Updated `README.md` for python instructions.
=> Added python instructions

sqlsetup.php
Added `unlink(__FILE__)` if the script is checked to have run successfully.
=> Added auto file removal after setup

README.md, bodies/add.php, bodies/delete.php, bodies/deleteuser.php, bodies/edit.php, bodies/edituser.php, bodies/index.php, bodies/panel.php, bodies/profile.php, scripts/readDB.py, template/footer.php, template/sidebar.php
- Added `output` div tag in the footer, removed them from everywhere else.
- Fixed the `readDB.py` script, as it previously wasn't made to work with multiple users.
=> Fixed media refresh
